// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:0
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-SZnTTwKeAFBitD96v94ei5m4hZckTt4',
    appId: '1:458423440277:android:438a33aea3d5264ff31c9c',
    messagingSenderId: '458423440277',
    projectId: 'instant-connect-ff3a0',
    storageBucket: 'instant-connect-ff3a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0o-jMhrNDbeS4q53VPdWbGOS7vBsu2A8',
    appId: '1:458423440277:ios:88f74ee95d5434eff31c9c',
    messagingSenderId: '458423440277',
    projectId: 'instant-connect-ff3a0',
    storageBucket: 'instant-connect-ff3a0.appspot.com',
    iosBundleId: 'com.example.instantConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0o-jMhrNDbeS4q53VPdWbGOS7vBsu2A8',
    appId: '1:458423440277:ios:88f74ee95d5434eff31c9c',
    messagingSenderId: '458423440277',
    projectId: 'instant-connect-ff3a0',
    storageBucket: 'instant-connect-ff3a0.appspot.com',
    iosBundleId: 'com.example.instantConnect',
  );

}